apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: infra-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8989
          env:
            - name: SERVER_PORT  # 이 부분을 추가해야 컨테이너 내부에서 8989로 뜹니다.
              value: "8989"
            - name: KAFKA_CLUSTERS_0_NAME
              value: "local-cluster"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: infra-dev
spec:
  type: LoadBalancer
  ports:
    - port: 8989
      targetPort: 8989
  selector:
    app: kafka-ui