apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: infra-dev
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: broker
      port: 9092
    - name: controller
      port: 9093
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: infra-dev
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: kafka
          image: apache/kafka:3.9.0
          ports:
            - containerPort: 9092
              name: broker
            - containerPort: 9093
              name: controller
          env:
            - name: KAFKA_CLUSTER_ID
              value: "MkU3OEVBNTcwNTJENDM2Qk"
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e

              NODE_ID=${HOSTNAME##*-}
              DATA_DIR=/var/lib/kafka/data/logs
              QUORUM=0@kafka-0.kafka.infra-dev.svc.cluster.local:9093,1@kafka-1.kafka.infra-dev.svc.cluster.local:9093,2@kafka-2.kafka.infra-dev.svc.cluster.local:9093

              cat > /tmp/kafka.properties << EOF
              node.id=${NODE_ID}
              process.roles=broker,controller
              controller.quorum.voters=${QUORUM}
              listeners=PLAINTEXT://:9092,CONTROLLER://:9093
              advertised.listeners=PLAINTEXT://${HOSTNAME}.kafka.infra-dev.svc.cluster.local:9092
              listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
              inter.broker.listener.name=PLAINTEXT
              controller.listener.names=CONTROLLER
              log.dirs=${DATA_DIR}
              offsets.topic.replication.factor=3
              transaction.state.log.replication.factor=3
              transaction.state.log.min.isr=2
              default.replication.factor=3
              min.insync.replicas=2
              EOF

              if [ ! -f "${DATA_DIR}/meta.properties" ]; then
                /opt/kafka/bin/kafka-storage.sh format \
                  -t ${KAFKA_CLUSTER_ID} \
                  -c /tmp/kafka.properties \
                  --ignore-formatted
              fi

              exec /opt/kafka/bin/kafka-server-start.sh /tmp/kafka.properties
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard-rwo
        resources:
          requests:
            storage: 5Gi
