apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: infra-dev
spec:
  serviceName: "redis-cluster"
  replicas: 6
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
        - name: redis
          image: redis:7.4-alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              export FULL_HOSTNAME="${HOSTNAME}.redis-cluster.infra-dev.svc.cluster.local"
              
              exec redis-server \
                --cluster-enabled yes \
                --cluster-config-file /data/nodes.conf \
                --cluster-node-timeout 15000 \
                --appendonly yes \
                --bind 0.0.0.0 \
                --protected-mode no \
                --cluster-preferred-endpoint-type hostname \
                --cluster-announce-hostname "${FULL_HOSTNAME}" \
                --cluster-announce-port 6379 \
                --cluster-announce-bus-port 16379
          ports:
            - containerPort: 6379
              name: redis
            - containerPort: 16379
              name: cluster-bus
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: infra-dev
spec:
  clusterIP: None
  selector:
    app: redis-cluster
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: bus
      port: 16379
      targetPort: 16379