apiVersion: apps/v1
kind: Deployment
metadata:
  name: waiting-service
  namespace: infra-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waiting-service
  template:
    metadata:
      labels:
        app: waiting-service
    spec:
      containers:
        - name: waiting-service
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Xlog:gc*:file=/tmp/gc.log:time,uptime,level,tags:filecount=5,filesize=10M
          envFrom:
            - configMapRef:
                name: waiting-service-env
          image: waiting-waiting-service:v13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "1000m"
              memory: "2Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: waiting-service
  namespace: infra-dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8081"
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31081
  selector:
    app: waiting-service
