# infra/base/monitoring/tempo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.8.3
          args: ["-config.file=/etc/tempo.yaml"]
          ports:
            - containerPort: 3200
            - containerPort: 4317
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo.yaml
              subPath: tempo-config.yaml
            - name: tempo-storage
              mountPath: /var/lib/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: http-metrics
      port: 3200
      targetPort: 3200
  selector:
    app: tempo