apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: waiting-service

resources:
  - waiting-deployment.yaml
  - waiting-service.yaml
  - waiting-ingress.yaml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      config: kustomize